channels:
  - conda-forge
dependencies:
  - matplotlib==2.2.2
  - appmode==0.4.0
  - pip
  - pip:
    - setuptools==39.1.0
    - numpy==1.14.3
    - ipywidgets==7.2.1
    - gensim==3.1.0
    - wordcloud==1.5.0
    - pandas==0.23.0
    - nltk==3.3
    - ipython==7.2.0
    - pyLDAvis==2.1.2
    - scikit-learn==0.20.1
    - vaderSentiment==3.2.1
    - xlrd==0.9.0
    - pivottablejs
